In [1]:
import numpy as np
import pandas as pd
from scipy.stats import ttest_rel, ttest_ind
from statsmodels.stats.multitest import multipletests

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statsmodels.graphics.factorplots import interaction_plot
import matplotlib.pyplot as plt
from scipy import stats

from scipy.stats import shapiro

# Figure 1
## 1d) - Expression differences of members of the pth gene family in response to different social environments
C$_{t}$ values as reported in S2

In [155]:
d = {'pth2 - isolated': [4.916,5.201,5.522,4.418,5.311,5.034,4.299,4.158,4.587,5.220], 
     'pth2 - social': [2.990,2.820,2.666,3.706,3.723,3.073,2.776,2.193,3.126,3.664],
    'pth1a - isolated': [4.107, 4.519, 4.336, 4.011, 2.352, 3.044, 3.789, 3.539, 4.733, 3.425],
    'pth1a - social': [4.877, 5.046, 4.854, 4.929, 3.544, 3.593, 4.289, 4.741, 3.431, 4.276],
    'pth1b - isolated': [-0.187, -0.143,-0.287, 1.146, 2.291,1.376, -0.089, -1.040, 0.494, 0.235],
    'pth1b - social': [-0.092,-0.296,-0.241,0.915,1.929,0.974,-0.581,-1.051,0.404,0.576],
    'pthla - isolated': [4.859,4.011,5.141,4.041,4.971,5.173,3.981,3.535,4.198,3.924],
    'pthla - social': [5.328,4.516,4.623,4.944,4.787,3.782,3.949,4.186,4.125,4.750],
    'pthlb - isolated': [8.514,8.067,8.542,7.680,10.390,8.702,7.936,7.869,8.173,8.308],
    'pthlb - social': [10.337,8.210,8.310,8.246,9.640,8.542,7.378,8.113,8.682,8.838],
    'pth4 - isolated': [4.892,4.082,4.644,3.761,5.194,5.129,4.172,3.591,4.519,4.379],
    'pth4 - social': [5.484,4.328,3.802,4.069,5.151,3.815,3.328,3.369,4.384,5.456]}
df = pd.DataFrame(data=d)
df.head()

pth2 - isolated  pth2 - social  pth1a - isolated  pth1a - social  \
0            4.916          2.990             4.107           4.877   
1            5.201          2.820             4.519           5.046   
2            5.522          2.666             4.336           4.854   
3            4.418          3.706             4.011           4.929   
4            5.311          3.723             2.352           3.544   

   pth1b - isolated  pth1b - social  pthla - isolated  pthla - social  \
0            -0.187          -0.092             4.859           5.328   
1            -0.143          -0.296             4.011           4.516   
2            -0.287          -0.241             5.141           4.623   
3             1.146           0.915             4.041           4.944   
4             2.291           1.929             4.971           4.787   

   pthlb - isolated  pthlb - social  pth4 - isolated  pth4 - social  
0             8.514          10.337            4.892          5.484  
1             8.067           8.210            4.082          4.328  
2             8.542           8.310            4.644          3.802  
3             7.680           8.246            3.761          4.069  
4            10.390           9.640            5.194          5.151

In [156]:
pvalues = []
[t, p] = ttest_rel(df['pth2 - isolated'], df['pth2 - social'])
print('For pth2, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)
[t, p] = ttest_rel(df['pth1a - isolated'], df['pth1a - social'])
print('For pth1a, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)
[t, p] = ttest_rel(df['pth1b - isolated'], df['pth1b - social'])
print('For pth1b, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)
[t, p] = ttest_rel(df['pthla - isolated'], df['pthla - social'])
print('For pthla, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)
[t, p] = ttest_rel(df['pthlb - isolated'], df['pthlb - social'])
print('For pthlb, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)
[t, p] = ttest_rel(df['pth4 - isolated'], df['pth4 - social'])
print('For pth4, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

For pth2, t = 9.818336030819468 and p = 2.083631937614688e-06
For pth1a, t = -2.54882884451511 and p = 0.015627371727670564
For pth1b, t = 1.5567921077943054 and p = 0.07697269970754803
For pthla, t = -0.5166201392269912 and p = 0.3089375633869814
For pthlb, t = -0.9187342265317263 and p = 0.19109856270501852
For pth4, t = 0.5126285172738125 and p = 0.3102773737945278


(array([ True, False, False, False, False, False]),
 array([2.50035833e-05, 9.37642304e-02, 3.07890799e-01, 6.20554748e-01,
        5.73295688e-01, 6.20554748e-01]),
 0.008512444610847103,
 0.008333333333333333)

Test for normality

In [159]:
# normality test
stat, p = shapiro(df['pth2 - isolated'])
print('Statistics=%.3f, p=%.3f' % (stat, p))

stat, p = shapiro(df['pth2 - social'])
print('Statistics=%.3f, p=%.3f' % (stat, p))

Statistics=0.936, p=0.509
Statistics=0.926, p=0.409


# Figure 2
## 2a) Time dynamics: Increase of pth2 levels correlate with time of exposure to conspecifics

In [160]:
d = {'isolated': [6.103,5.369,5.428,4.213,4.649,5.294,4.485,7.203,4.690,5.071,6.337,4.297,4.777,4.984,5.292,5.319,4.565],
     '30 min': [5.636, 4.858,5.322,3.889,4.119,4.369,5.259,5.667,4.652,4.157,4.475,4.580,4.716,4.610,4.599,np.nan, np.nan],
     '60 min': [5.637,4.997,3.957,4.148,4.006,4.039,4.107,4.652,4.481,4.887, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
     '180 min': [2.922,3.517,3.619,3.263,5.019,3.503,4.202,4.049,3.631,3.979,np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
     '12 hours': [4.140,3.287,3.104,2.511,2.735,2.622,2.938,2.653, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
     'social': [4.500,3.336,3.103,2.320,2.793,2.720,2.055,4.513,2.857,3.014,2.036,2.253,3.148,2.648,3.230,2.847,2.630]
}

df = pd.DataFrame(data=d)
df.head()

isolated  30 min  60 min  180 min  12 hours  social
0     6.103   5.636   5.637    2.922     4.140   4.500
1     5.369   4.858   4.997    3.517     3.287   3.336
2     5.428   5.322   3.957    3.619     3.104   3.103
3     4.213   3.889   4.148    3.263     2.511   2.320
4     4.649   4.119   4.006    5.019     2.735   2.793

In [161]:
pvalues = []
[t, p] = ttest_ind(df['isolated'].dropna(),df['30 min'].dropna())
print('For 30 min, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_ind(df['isolated'].dropna(),df['60 min'].dropna())
print('For 60 min, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_ind(df['isolated'].dropna(),df['180 min'].dropna())
print('For 180 min, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_ind(df['isolated'].dropna(),df['12 hours'].dropna())
print('For 12 hours, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_ind(df['isolated'].dropna(),df['social'].dropna())
print('For social conditions, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

multipletests(pvalues, alpha=0.05, method='fdr_tsbh', is_sorted=False, returnsorted=False)

For 30 min, t = 1.8922402114296208 and p = 0.0340726057789864
For 60 min, t = 2.45013516874614 and p = 0.010812224586491411
For 180 min, t = 4.9546423012616 and p = 2.0956611347314803e-05
For 12 hours, t = 7.134543928544459 and p = 1.4423897122561982e-07
For social conditions, t = 8.783439730638207 and p = 2.4503498436730134e-10


(array([ True,  True,  True,  True,  True]),
 array([1.36290423e-02, 5.40611229e-03, 1.39710742e-05, 1.44238971e-07,
        4.90069969e-10]),
 0.010206218313011495,
 0.01)

## 2b) Decrease of pth2 levels after short term social isolation

In [49]:
d = {'isolated': [5.370,5.604,5.900,4.581,4.656,5.780,4.083,4.869,3.719,4.497,5.167,4.468,4.857],
    '3 hours': [3.182,3.507,3.086,3.250,3.969,3.511,2.799,2.447,2.233, np.nan, np.nan, np.nan, np.nan],
    '6 hours': [4.074,4.413,4.252,np.nan, np.nan, np.nan, np.nan, np.nan,np.nan, np.nan, np.nan, np.nan, np.nan],
    'social': [3.252,3.107,3.074,2.852,3.340,3.922,2.535,1.707,2.117,1.916,2.953,3.197, np.nan]}
df = pd.DataFrame(data = d)
df.head()

isolated  3 hours  6 hours  social
0     5.370    3.182    4.074   3.252
1     5.604    3.507    4.413   3.107
2     5.900    3.086    4.252   3.074
3     4.581    3.250      NaN   2.852
4     4.656    3.969      NaN   3.340

In [52]:
pvalues = []
[t, p] = ttest_ind(df['social'].dropna(),df['3 hours'].dropna())
print('For 3 hours, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_ind(df['social'].dropna(),df['6 hours'].dropna())
print('For 6 hours, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

For 3 hours, t = -1.0401920159552156 and p = 0.15565361352597956
For 6 hours, t = -3.659605880548592 and p = 0.0014419732748514522


(array([False,  True]),
 array([0.31130723, 0.00576789]),
 0.025320565519103666,
 0.025)

## 2c) pth2 dynamics at the juvenile stage

In [54]:
d = {'social': [3.733,4.370,4.000,3.305,3.385],
    '24 hours': [5.594, 5.834,5.647,4.703,4.384],
    'isolated': [5.315,5.601,5.527,4.784,4.924]}

df = pd.DataFrame(data=d)
df.head()

social  24 hours  isolated
0   3.733     5.594     5.315
1   4.370     5.834     5.601
2   4.000     5.647     5.527
3   3.305     4.703     4.784
4   3.385     4.384     4.924

In [59]:
pvalues = []
[t, p] = ttest_rel(df['social'].dropna(),df['isolated'].dropna())
print('For social conditions, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_rel(df['isolated'].dropna(),df['24 hours'].dropna())
print('For 24 hours isolation, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

For social conditions, t = -23.603345885760536 and p = 9.550978099311588e-06
For 24 hours isolation, t = -0.014754358310279174 and p = 0.4944673665483954


(array([ True, False]),
 array([3.82039124e-05, 9.88934733e-01]),
 0.025320565519103666,
 0.025)

## Figure 2d) pth2 dynamics in adult zebrafish


In [2]:
d = {'isolated': [2.474,1.713,1.999, np.nan],
    'social': [0.727,0.302,0.816,0.932],
    'short social': [0.363,0.854,0.985,0.540],
    'short iso': [3.489,3.591,3.192,3.426]}

df = pd.DataFrame(data=d)
df.head()

isolated  social  short social  short iso
0     2.474   0.727         0.363      3.489
1     1.713   0.302         0.854      3.591
2     1.999   0.816         0.985      3.192
3       NaN   0.932         0.540      3.426

In [6]:
pvalues = []

[t, p] = ttest_ind(df['short social'].dropna(),df['isolated'].dropna())
print('comparing short social and isolated, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p/2)

[t, p] = ttest_ind(df['short social'].dropna(),df['social'].dropna())
print('comparing short social and social, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p/2)

[t, p] = ttest_ind(df['short iso'].dropna(),df['social'].dropna())
print('comparing short isolation and social, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p/2)

[t, p] = ttest_ind(df['short iso'].dropna(),df['isolated'].dropna())
print('comparding short isolation and isolated, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p/2)

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

comparing short social and isolated, t = -5.490297510789816 and p = 0.0013681014836495308
comparing short social and social, t = -0.04423416862896142 and p = 0.48307657234585033
comparing short isolation and social, t = 16.926277706574503 and p = 1.3591597835397753e-06
comparding short isolation and isolated, t = 6.458645684578994 and p = 0.0006622502007027491


(array([ True, False,  True,  True]),
 array([1.82413531e-03, 4.83076572e-01, 5.43663913e-06, 1.32450040e-03]),
 0.012741455098566168,
 0.0125)

# Figure 3
## 3b) chemosensory rescue attempt

In [72]:
d = {'isolated': [5.862,5.877,5.645],
    'medium swap': [5.522,6.056,5.910],
    'social': [3.284, 3.414, 2.703]} 

df = pd.DataFrame(data=d)
df.head()

isolated  medium swap  social
0     5.862        5.522   3.284
1     5.877        6.056   3.414
2     5.645        5.910   2.703

In [74]:
pvalues = []
[t, p] = ttest_rel(df['social'].dropna(),df['isolated'].dropna())
print('comparing social and isolated, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_rel(df['medium swap'].dropna(),df['isolated'].dropna())
print('comparing isolated and chemosensory rescue, t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

comparing social and isolated, t = -18.431967920580387 and p = 0.0014652585395614993
comparing isolated and chemosensory rescue, t = 0.18344947948338597 and p = 0.4356797111112813


(array([ True, False]),
 array([0.00586103, 0.87135942]),
 0.025320565519103666,
 0.025)

## 3d) Visual Rescue Attempt

In [75]:
d = {'age': [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21],
    'visual': [0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,
              0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1],
    'physical': [0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,
                0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1],
    'value': [5.531,6.070,5.900,6.244,6.190,
              4.932,5.204,5.539,6.016,4.981,
              3.786,4.548,4.098,4.077,4.993,
              3.802,4.790,3.887,4.371,4.576,
              5.655,5.718,6.042,5.552,5.661,5.583,
              5.541,6.621,5.727,5.095,5.031,5.454,
              4.702,4.778,4.762,4.498,4.296,4.998,
              5.114,4.937,5.330,4.060,4.915,4.448]}

df = pd.DataFrame(data = d)
df.head()

age  visual  physical  value
0    5       0         0  5.531
1    5       0         0  6.070
2    5       0         0  5.900
3    5       0         0  6.244
4    5       0         0  6.190

In [98]:
# 5 dpf
df5dpf = df[df['age']==5]

formula = 'value ~ visual + physical + visual:physical'
model = ols(formula, df5dpf).fit()
aov_table = anova_lm(model, typ=2)
print(aov_table.round(6))

# 21 dpf
df21dpf = df[df['age']==21]

formula = 'value ~ visual + physical + visual:physical'
model = ols(formula, df21dpf).fit()
aov_table = anova_lm(model, typ=2)
print(aov_table.round(6))


                   sum_sq    df          F    PR(>F)
visual           0.557446   1.0   3.213884  0.091941
physical         9.355752   1.0  53.939397  0.000002
visual:physical  0.507848   1.0   2.927936  0.106372
Residual         2.775189  16.0        NaN       NaN
                   sum_sq    df          F    PR(>F)
visual           0.000033   1.0   0.000204  0.988736
physical         4.897873   1.0  30.641831  0.000020
visual:physical  0.095256   1.0   0.595936  0.449159
Residual         3.196854  20.0        NaN       NaN


Since there is apparently no interaction effect, no post-hoc tests need to be performed. 

## 3e) Comparison of social rescue with and without light.

In [99]:
d = {'isolated':[5.336,5.718,5.740,6.304,6.211,5.929],
    'light':[3.402,4.056,4.867,4.710,4.897,4.276],
    'dark':[4.261,5.221,4.624,4.879,4.655,4.567]}

df = pd.DataFrame(data=d)
df.head()

isolated  light   dark
0     5.336  3.402  4.261
1     5.718  4.056  5.221
2     5.740  4.867  4.624
3     6.304  4.710  4.879
4     6.211  4.897  4.655

In [101]:
pvalues = []

[t, p] = ttest_rel(df['isolated'].dropna(),df['light'].dropna())
print('comparing isolated and social (light), t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_rel(df['isolated'].dropna(),df['dark'].dropna())
print('comparing isolated and social (dark), t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

[t, p] = ttest_rel(df['light'].dropna(),df['dark'].dropna())
print('comparing social (light) and social (dark), t = '+ str(t) + ' and p = ' + str(p/2))
pvalues.append(p)

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

comparing isolated and social (light), t = 10.037646730561294 and p = 8.39471166533326e-05
comparing isolated and social (dark), t = 7.58665609686374 and p = 0.0003157879102815708
comparing social (light) and social (dark), t = -1.4163586870605946 and p = 0.10792224230982565


(array([ True,  True, False]),
 array([0.00050368, 0.00094736, 0.21584448]),
 0.016952427508441503,
 0.016666666666666666)

# Figure 4
## 4b) Impact of lateral line ablation

In [125]:
d = {'E3_iso': [8.132,7.327,6.928,3.923,5.438,4.720,4.787,4.837,5.123],
    'E3_soc': [5.769,5.128,4.251,3.243,3.635,3.861,3.525,3.979,3.538],
    'CuSO4_iso': [6.472,6.925,5.194,4.593,6.217, np.nan, np.nan, np.nan, np.nan],
    'CuSO4_soc': [6.859,6.784,4.323,4.439,5.093, np.nan, np.nan, np.nan, np.nan],
    'Neo_iso': [4.878,5.018,4.808,5.203,4.678, np.nan, np.nan, np.nan, np.nan],
    'Neo_soc': [4.545,5.229,4.620,4.365,4.640, np.nan, np.nan, np.nan, np.nan]}

df = pd.DataFrame(data=d)
df.head()

E3_iso  E3_soc  CuSO4_iso  CuSO4_soc  Neo_iso  Neo_soc
0   8.132   5.769      6.472      6.859    4.878    4.545
1   7.327   5.128      6.925      6.784    5.018    5.229
2   6.928   4.251      5.194      4.323    4.808    4.620
3   3.923   3.243      4.593      4.439    5.203    4.365
4   5.438   3.635      6.217      5.093    4.678    4.640

In [126]:
pvalues = []

[t, p] = ttest_rel(df['E3_iso'].dropna(), df['E3_soc'].dropna())
pvalues.append(p)
print('For untreated animals, t = ' + str(t) + ' p = ' + str(p))

[t, p] = ttest_rel(df['CuSO4_iso'].dropna(), df['CuSO4_soc'].dropna())
pvalues.append(p)
print('For CuSO4-treated animals, t = ' + str(t) + ' p = ' + str(p))

[t, p] = ttest_rel(df['Neo_iso'].dropna(), df['Neo_soc'].dropna())
pvalues.append(p)
print('For Neomycin-treated animals, t = ' + str(t) + ' p = ' + str(p))

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

For untreated animals, t = 6.571262910391263 p = 0.00017454549429944867
For CuSO4-treated animals, t = 1.3938955189093376 p = 0.23579614130931398
For Neomycin-treated animals, t = 1.354739985557677 p = 0.24696415796455468


(array([ True, False, False]),
 array([0.00052364, 0.24696416, 0.24696416]),
 0.016952427508441503,
 0.016666666666666666)

## 4c) Presence of artemia

In [109]:
d = {'isolated': [5.569,5.559,5.426,6.269,6.556,6.335],
    'artemia14': [4.776,5.610,5.306, np.nan, np.nan, np.nan],
    'artemia1000': [np.nan, np.nan, np.nan,6.132, 6.543, 7.352],
    'social': [np.nan, np.nan, np.nan, 3.919, 4.667, 4.308]}

df = pd.DataFrame(data=d)
df.head()

isolated  artemia14  artemia1000  social
0     5.569      4.776          NaN     NaN
1     5.559      5.610          NaN     NaN
2     5.426      5.306          NaN     NaN
3     6.269        NaN        6.132   3.919
4     6.556        NaN        6.543   4.667

In [124]:
pvalues = []

[t, p] = ttest_rel(df['isolated'].iloc[0:3], df['artemia14'].iloc[0:3])
pvalues.append(p)
print('Addition of 14 artemia results in t = ' + str(t) + ' and p = ' + str(p))

[t, p] = ttest_rel(df['isolated'].iloc[3:7], df['artemia1000'].iloc[3:7])
pvalues.append(p)
print('Addition of 1000 artemia results in t = ' + str(t) + ' and p = ' + str(p))

[t, p] = ttest_rel(df['isolated'].iloc[3:7], df['social'].iloc[3:7])
pvalues.append(p)
print('Addition of 14 zebrafish results in t = ' + str(t) + ' and p = ' + str(p))

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

Addition of 14 artemia results in t = 1.1153934655503712 and p = 0.38072890915484936
Addition of 1000 artemia results in t = -0.7901445982484151 and p = 0.5122497752889774
Addition of 14 zebrafish results in t = 15.289886630578483 and p = 0.00425026281297711


(array([False, False,  True]),
 array([0.51224978, 0.51224978, 0.01275079]),
 0.016952427508441503,
 0.016666666666666666)

# 4e) Impact of mechanical stimulation

In [150]:
d = {'isolated': [4.872,5.272,4.589,4.506,4.941,
                  4.589,4.506,4.941,5.019,4.847,
                  6.272,4.884,4.769,6.565,4.990,
                  4.309,4.423,4.206,4.895,4.733,
                  5.263,5.169,4.634,4.901,5.572,
                  4.614,5.017,4.067],
    'periodic': [4.289,4.944,4.891,4.522,4.706,
                 4.891,4.522,4.706,np.nan,np.nan,
                 np.nan, np.nan, np.nan, np.nan, np.nan,
                 np.nan, np.nan, np.nan, np.nan, np.nan,
                 np.nan, np.nan, np.nan, np.nan, np.nan,
                 np.nan, np.nan, np.nan],
    '3 hours': [np.nan, np.nan, np.nan, np.nan, np.nan,
                np.nan, np.nan, np.nan, 4.263, 4.037,
                5.486,4.631,4.944,5.731,4.623,
                4.432,3.764,3.851,np.nan, np.nan, 
                np.nan, np.nan, np.nan, np.nan, np.nan,
                np.nan, np.nan, np.nan],
    '6 hours': [np.nan, np.nan, np.nan, np.nan, np.nan,
                np.nan, np.nan, np.nan, np.nan, np.nan,
                np.nan, np.nan, np.nan, np.nan, np.nan,
                np.nan, np.nan, np.nan, 4.217,4.266,
                4.185,4.293,4.423,4.254,4.188,
                4.395,3.666,3.623]}

df = pd.DataFrame(data=d)
df.head()

isolated  periodic  3 hours  6 hours
0     4.872     4.289      NaN      NaN
1     5.272     4.944      NaN      NaN
2     4.589     4.891      NaN      NaN
3     4.506     4.522      NaN      NaN
4     4.941     4.706      NaN      NaN

In [151]:
pvalues = []

[t, p] = ttest_rel(df['isolated'].iloc[0:8], df['periodic'].iloc[0:8])
pvalues.append(p)
print('For periodic stimulation, t = ' + str(t) + ' and p = ' + str(p))

[t, p] = ttest_rel(df['isolated'].iloc[8:18], df['3 hours'].iloc[8:18])
pvalues.append(p)
print('For 3 hours of random stimulation, t = ' + str(t) + ' and p = ' + str(p))

[t, p] = ttest_rel(df['isolated'].iloc[18:28], df['6 hours'].iloc[18:28])
pvalues.append(p)
print('For 6 hours of random stimulation, t = ' + str(t) + ' and p = ' + str(p))

multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

For periodic stimulation, t = 0.8504497340075354 and p = 0.42320753025009483
For 3 hours of random stimulation, t = 3.761233161640674 and p = 0.004476493708684494
For 6 hours of random stimulation, t = 5.437773976058705 and p = 0.00041217482919133643


(array([False,  True,  True]),
 array([0.42320753, 0.00671474, 0.00123652]),
 0.016952427508441503,
 0.016666666666666666)

In [152]:
ttest_ind(df['6 hours'].iloc[18:28],df['3 hours'].iloc[8:18])

Ttest_indResult(statistic=-1.8817136316265357, pvalue=0.07614800560969336)

# Supplemental figures

# Adults
Most of our results were obtained from larval or juvenile zebrafish. At these stages, sexual differentiation has not taken place yet. We adressed the question whether sex is a factor in pth2 expression strength at later, adult stages of development.

In [4]:
d = {'male': [0.157,0.254,-0.419,-0.329],
    'female': [0.093,-0.035,-0.280,-0.453]}

df = pd.DataFrame(data=d)
df.head()

male  female
0  0.157   0.093
1  0.254  -0.035
2 -0.419  -0.280
3 -0.329  -0.453

In [5]:
[t, p] = ttest_ind(df['male'], df['female'])
print('Comparing pth2 levels of males and females, t = ' + str(t) + ' and p = ' + str(p))

Comparing pth2 levels of males and females, t = 0.4043141263942289 and p = 0.6999994670017485


In [6]:
d = {'5': [1.354,1.926,2.082,1.916,2.387,1.790],
    '35': [1.094,1.277,1.377,1.972,1.618,1.376]}

df = pd.DataFrame(data=d)
df.head()

5     35
0  1.354  1.094
1  1.926  1.277
2  2.082  1.377
3  1.916  1.972
4  2.387  1.618

In [9]:
[t, p] = ttest_ind(df['5'], df['35'])
print('Comparing pth2 levels in adults of different densities, t = ' + str(t) + ' and p = ' + str(p))

Comparing pth2 levels in adults of different densities, t = 2.442944835707187 and p = 0.034673841476036096


## Additional piezo results
As we do not show all experiments we performed with artificial mechanical stimulation (piezo-paradigm), we provide a more comprehensive list in the supplements.

In [14]:
## 70 Hz - continuous stimulation
d = {'isolated70cont':[4.890,5.970,5.018,6.747,5.424,5.239],
     'piezo70cont':[8.0276,6.408,6.375,5.259,5.115,4.708],
    # 70 Hz - with kin-imbued water
     'isolated70contKIW':[4.386,5.163, np.nan, np.nan, np.nan, np.nan],
     'piezo70contKIW':[4.347,5.289, np.nan, np.nan, np.nan, np.nan],
    # 70 Hz, two piezo pieces, 300 msec
     'isolated70_2_300': [4.589,4.506,4.941, np.nan, np.nan, np.nan],
     'piezo70_2_300': [4.891,4.522,4.706, np.nan, np.nan, np.nan],
    # 70 Hz, two piezo pieces, 5000 msec
     'isolated70_2_5000': [4.769,4.300, np.nan, np.nan, np.nan, np.nan],
     'piezo70_2_5000': [4.426,4.620, np.nan, np.nan, np.nan, np.nan],
    # 70 Hz, two piezo pieces + rubber, 300 msec
     'isolated70_2r_300': [4.523,4.075,4.334, np.nan, np.nan, np.nan],
     'piezo70_2r_300': [4.412,4.508,4.346, np.nan, np.nan, np.nan],
    # 70 Hz, two piezo pieces + rubber, 500 msec
     'isolated70_2r_500': [3.847,4.284, np.nan, np.nan, np.nan, np.nan],
     'piezo70_2r_500': [4.171,3.880, np.nan, np.nan, np.nan, np.nan], 
    # 70 Hz, two piezo pieces + rubber, 700 msec
     'isolated70_2r_700': [4.480,5.042,5.383, np.nan, np.nan, np.nan],
     'piezo70_2r_700': [5.900,5.419,4.924, np.nan, np.nan, np.nan],  
    # 70 Hz, two piezo pieces + rubber, 800 msec
     'isolated70_2r_800': [4.757,4.294,5.384,4.996,5.501, np.nan],
     'piezo70_2r_800': [4.510,4.438,4.893,7.979,5.773, np.nan]     
    }

df = pd.DataFrame(data=d)
df.head(10)

isolated70cont  piezo70cont  isolated70contKIW  piezo70contKIW  \
0           4.890       8.0276              4.386           4.347   
1           5.970       6.4080              5.163           5.289   
2           5.018       6.3750                NaN             NaN   
3           6.747       5.2590                NaN             NaN   
4           5.424       5.1150                NaN             NaN   
5           5.239       4.7080                NaN             NaN   

   isolated70_2_300  piezo70_2_300  isolated70_2_5000  piezo70_2_5000  \
0             4.589          4.891              4.769           4.426   
1             4.506          4.522              4.300           4.620   
2             4.941          4.706                NaN             NaN   
3               NaN            NaN                NaN             NaN   
4               NaN            NaN                NaN             NaN   
5               NaN            NaN                NaN             NaN   

   isolated70_2r_300  piezo70_2r_300  isolated70_2r_500  piezo70_2r_500  \
0              4.523           4.412              3.847           4.171   
1              4.075           4.508              4.284           3.880   
2              4.334           4.346                NaN             NaN   
3                NaN             NaN                NaN             NaN   
4                NaN             NaN                NaN             NaN   
5                NaN             NaN                NaN             NaN   

   isolated70_2r_700  piezo70_2r_700  isolated70_2r_800  piezo70_2r_800  
0              4.480           5.900              4.757           4.510  
1              5.042           5.419              4.294           4.438  
2              5.383           4.924              5.384           4.893  
3                NaN             NaN              4.996           7.979  
4                NaN             NaN              5.501           5.773  
5                NaN             NaN                NaN             NaN

In [12]:
pvalues = []
# 70 Hz, continuous stimulation
[t, p] = ttest_rel(df['isolated70cont'].dropna(), df['piezo70cont'].dropna())
pvalues.append(p)
print('for continued stimulation with 70 Hz, t = ' + str(t) + ' and p = ' + str(p))

# 70 Hz, continuous stimulation + kin-imbued water
[t, p] = ttest_rel(df['isolated70contKIW'].dropna(), df['piezo70contKIW'].dropna())
pvalues.append(p)
print('for continued stimulation with 70 Hz in the presence of kin-imbued water, t = ' + str(t) + ' and p = ' + str(p))

# 70 Hz, 300 msec stimulation with two-ended piezo
[t, p] = ttest_rel(df['isolated70_2_300'].dropna(), df['piezo70_2_300'].dropna())
pvalues.append(p)
print('for stimulation with 70 Hz (300 msec interval) with a two-ended piezo, t = ' + str(t) + ' and p = ' + str(p))

# 70 Hz, 5000 msec stimulation with two-ended piezo
[t, p] = ttest_rel(df['isolated70_2_5000'].dropna(), df['piezo70_2_5000'].dropna())
pvalues.append(p)
print('for stimulation with 70 Hz (5000 msec interval) with a two-ended piezo, t = ' + str(t) + ' and p = ' + str(p))

# 70 Hz, 300 msec stimulation with two-ended piezo + rubber
[t, p] = ttest_rel(df['isolated70_2r_300'].dropna(), df['piezo70_2r_300'].dropna())
pvalues.append(p)
print('for stimulation with 70 Hz (300 msec interval) with a two-ended piezo and rubber extension, t = ' + str(t) + ' and p = ' + str(p))

# 70 Hz, 500 msec stimulation with two-ended piezo + rubber
[t, p] = ttest_rel(df['isolated70_2r_500'].dropna(), df['piezo70_2r_500'].dropna())
pvalues.append(p)
print('for stimulation with 70 Hz (500 msec interval) with a two-ended piezo and rubber extension, t = ' + str(t) + ' and p = ' + str(p))


# 70 Hz, 700 msec stimulation with two-ended piezo + rubber
[t, p] = ttest_rel(df['isolated70_2r_700'].dropna(), df['piezo70_2r_700'].dropna())
pvalues.append(p)
print('for stimulation with 70 Hz (700 msec interval) with a two-ended piezo and rubber extension, t = ' + str(t) + ' and p = ' + str(p))


# 70 Hz, 800 msec stimulation with two-ended piezo + rubber
[t, p] = ttest_rel(df['isolated70_2r_800'].dropna(), df['piezo70_2r_800'].dropna())
pvalues.append(p)
print('for stimulation with 70 Hz (800 msec interval) with a two-ended piezo and rubber extension, t = ' + str(t) + ' and p = ' + str(p))


# correcting for multiple testing
multipletests(pvalues, alpha=0.05, method='fdr_bh', is_sorted=False, returnsorted=False)

for continued stimulation with 70 Hz, t = -0.6510176314629132 and p = 0.5437643744670104
for continued stimulation with 70 Hz in the presence of kin-imbued water, t = -0.5272727272727284 and p = 0.6910949024451758
for stimulation with 70 Hz (300 msec interval) with a two-ended piezo, t = -0.1783470416587776 and p = 0.8748806117176366
for stimulation with 70 Hz (5000 msec interval) with a two-ended piezo, t = 0.034690799396681266 and p = 0.9779240041418579
for stimulation with 70 Hz (300 msec interval) with a two-ended piezo and rubber extension, t = -0.6759513415438768 and p = 0.5687582584700501
for stimulation with 70 Hz (500 msec interval) with a two-ended piezo and rubber extension, t = 0.10989010989010935 and p = 0.9303213616722098
for stimulation with 70 Hz (700 msec interval) with a two-ended piezo and rubber extension, t = -0.8205820588864406 and p = 0.49812714373933153
for stimulation with 70 Hz (800 msec interval) with a two-ended piezo and rubber extension, t = -0.84792348858

(array([False, False, False, False, False, False, False, False]),
 array([0.977924, 0.977924, 0.977924, 0.977924, 0.977924, 0.977924,
        0.977924, 0.977924]),
 0.006391150954545011,
 0.00625)

# Figure S3 - impact of genotype on pth2 transcription

In [2]:
# S3a

S3a = {'isolated':[5.491, 7.198, 3.960, 4.200, 5.568, 4.302, 5.828],
     'social':[3.932, 4.461, 1.164, 1.516, 3.699, 2.961, 4.516]}

S3b = {'visual': [0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1],
    'physical': [0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1],
    'value': [5.697, 5.460, 6.254, 6.221, 5.689, 6.025,
             5.243, 4.755, 5.597, 6.093, 5.428, 5.818,
             3.386, 3.208, 3.914, 4.375, 3.586, 3.586,
             3.704, 3.429, 3.436, 4.146, 3.632, 4.335]}

S3a = pd.DataFrame(data = S3a)
S3b = pd.DataFrame(data = S3b)

In [10]:
[t, p] = ttest_rel(S3a['isolated'], S3a['social'])
print('for mitfa-/- fish, there is a difference between socially reared and isolated animals with t = ' + str(t) + ' and p = ' + str(p))


for mitfa-/- fish, there is a difference between socially reared and isolated animals with t = 7.980665396844242 and p = 0.00020621437416382658


In [6]:
formula = 'value ~ visual + physical + visual:physical'
model = ols(formula, S3b).fit()
aov_table = anova_lm(model, typ=2)
print(aov_table.round(8))

                    sum_sq    df           F    PR(>F)
visual            0.132759   1.0    0.833312  0.372190
physical         23.094702   1.0  144.962228  0.000000
visual:physical   0.384813   1.0    2.415420  0.135828
Residual          3.186306  20.0         NaN       NaN
